## default connection pool
debug: true
spring:
  sql:
    init:
      platform: postgresql
      mode: always
    output:
      ansi:
        enabled: always
  datasource:
    url: jdbc:postgresql://mouse.db.elephantsql.com/krolntwr
    username: ${PGSQL_DB}
    password: ${PGSQL_PWD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  data:
    mongodb:
      uri:  mongodb+srv://doubleshot_admin:${MONGODB_PWD}@doubleshot.eeydcch.mongodb.net/doubleshot?retryWrites=true&w=majority
      database: doubleshot

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR